openapi: 3.0.1

info:
  title: Do It App
  description: This service is for the management and storage of Do It App data.
  version: "1.0.0"

paths:
  /somepath:
    get:
      operationId: getSomepath
      responses:
        200:
          description: OK
          content:
            schema:
             {}
